### ISSUE TITLE
选择文本setSelection()方法异常

### ISSUE THREAD

**Issue by flymorn** [Vove7/Android-Accessibility-Api#8]
setSelection 函数执行的时候，系统报错：

`E/TextClassifierImpl: Error getting assist info.
    java.io.FileNotFoundException: No file for null locale
        at android.view.textclassifier.TextClassifierImpl.getSmartSelection(TextClassifierImpl.java:192)
        at android.view.textclassifier.TextClassifierImpl.classifyText(TextClassifierImpl.java:146)
        at android.widget.SelectionActionModeHelper$TextClassificationHelper.classifyText(SelectionActionModeHelper.java:463)
        at android.widget.SelectionActionModeHelper.-android_widget_SelectionActionModeHelper-mthref-1(SelectionActionModeHelper.java:83)
        at android.widget.-$Lambda$tTszxdFZ0V9nXhnBpPsqeBMO0fw$5.$m$0(Unknown Source:4)
        at android.widget.-$Lambda$tTszxdFZ0V9nXhnBpPsqeBMO0fw$5.get(Unknown Source:0)
        at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.doInBackground(SelectionActionModeHelper.java:369)
        at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.doInBackground(SelectionActionModeHelper.java:364)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

自带的demo，也是报错，烦请检查下呢。

**Comment by Vove7** [comment]
我这里设备 测试没问题的，可能系统版本兼容问题，可以多试几个设备看看

**Comment by flymorn** [comment]
测试机型：小米5 MIUI 10.8 开发版  ，Android 8.0.0，选择文本出问题
